
# This file was hand modified after being programmatically generated by MM

# To use this to build a jar:
#   In a new gemset, "gem install cucumber rspec-expectations rspec-core warbler"
#   Update version numbers below
#   cd ~/Projects/cukejar
#   warble gemjar jar

Gem::Specification.new do |s|
	s.name	=	"cukejar"
	s.version	=	"0.0.1"
	s.authors	=	["Art Griesser"]
	s.email	=	["a.griesser@prometheuscomputing.com"]
	s.summary	=	"Collects cucumber gems"
	s.description	=	"Used (with Warbler) to create a cucumber jar for use with JRuby"
	s.require_paths	=	[
	    'lib',
			# These are the gems installed in a fresh rvm gemset when you do "gem install cucumber"
			'../gems/gherkin-4.1.3/lib',
			'../gems/cucumber-core-1.5.0/lib',
			'../gems/builder-3.2.3/lib',
			'../gems/diff-lcs-1.3/lib',
			'../gems/multi_json-1.12.2/lib',
			'../gems/multi_test-0.1.2/lib',
			'../gems/cucumber-wire-0.0.1/lib',
			'../gems/cucumber-2.4.0/lib',
			# Cucumber works with RSpec expections
			'../gems/rspec-support-3.6.0/lib',
      '../gems/rspec-expectations-3.6.0/lib',
			'../gems/rspec-core-3.6.0/lib',
			]
	s.files	=	["mri.gemspec"]
	s.test_files	=	[]
	# These executables were manually copied from .rvm/gems/jruby-9.1.7.0@only_cucumber/bin into cukejar/bin
	# I don't like this, and didn't find a way to specify them without copying.
	# I didn't copy any rspec executables. I've not tested the cucumber executables.
	s.executables	=	['cucumber', 'gherkin-ruby', 'htmldiff', 'ldiff']
	s.add_dependency("gherkin", "~> 4.1.3")
	s.add_dependency("cucumber-core", "~> 1.5.0")
	s.add_dependency("builder", "~> 3.2.3")
	s.add_dependency("diff-lcs", "~> 1.3")
	s.add_dependency("multi_json", "~> 1.12.2")
	s.add_dependency("multi_test", "~> 0.1.2")
	s.add_dependency("cucumber-wire", "~> 0.0.1")
	s.add_dependency("cucumber", "~> 2.4.0")
	s.add_dependency("rspec-support", "~> 3.6.0")
	s.add_dependency("rspec-expectations", "~> 3.6.0")
	s.add_dependency("rspec-core", "~> 3.6.0")
end
